[general]
import = ["mandacaru.toml"]
live_config_reload = true

[font]
normal = { family = "Mononoki Nerd Font Mono" }
size = 16

[font.offset]
y = 2

[font.glyph_offset]
y = 1

[window]
option_as_alt = "Both"
