"$schema" = 'https://starship.rs/config-schema.json'

# [](fg:highlight_med)\
# [](fg:highlight_med)\
# [](fg:highlight_med)\
# [](fg:highlight_med)\
#
format = """
[](fg:highlight_med)\
$username\
[󱑽](highlight_med)\
$directory\
[󱑽](highlight_med)\
$git_branch\
[󱑽](highlight_med)\
$git_status\
[](highlight_med)\
$fill\
[](fg:highlight_med)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
[󱑽](highlight_med)\
$time\
[](highlight_med)\
\n \
[󱞪](fg:cactus) \
"""

palette = "mandacaru"

[palettes.mandacaru]
highlight_med = '#6c473d'
mandacaru = '#d2a0c6'
sky = '#a7d9e6'
sand = '#f8cf91'
text = '#f8f8eb'
land = '#fdaf05'
cactus = '#a7e39c'
flower = '#e0647e'

[username]
disabled = false
format = "[ 󰶵 $user ]($style)"
show_always = true
style_root = "bg:highlight_med fg:cactus"
style_user = "bg:highlight_med fg:cactus"

[directory]
format = "[ $path ]($style)"
style = "bg:highlight_med fg:text"
truncation_length = 1
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙 "
Downloads = " "
Music = " "
Pictures = " "

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "bg:highlight_med fg:land"
symbol = ""

[git_status]
disabled = false
style = "bg:highlight_med fg:mandacaru"
format = '([$all_status$ahead_behind]($style))'
up_to_date = '[ ✓ ](bg:highlight_med fg:cactus)'
untracked = '[?\($count\)](bg:highlight_med fg:sky)'
stashed = '[\$](bg:highlight_med fg:cactus)'
modified = '[!\($count\)](bg:highlight_med fg:sky)'
renamed = '[»\($count\)](bg:highlight_med fg:cactus)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:highlight_med fg:sky)'
ahead = '[⇡\(${count}\)](bg:highlight_med fg:land)'
diverged = '⇕[\[](bg:highlight_med fg:cactus)[⇡\(${ahead_count}\)](bg:highlight_med fg:land)[⇣\(${behind_count}\)](bg:highlight_med fg:sand)[\]](bg:highlight_med fg:cactus)'
behind = '[⇣\(${count}\)](bg:highlight_med fg:sand)'

[time]
disabled = false
format = "[ $time 󰴈 ]($style)"
style = "bg:highlight_med fg:sand"
time_format = "%I:%M"
use_12hr = false

# Languages

[c]
style = "bg:highlight_med fg:flower"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = " "

[elixir]
style = "bg:highlight_med fg:flower"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = " "

[elm]
style = "bg:highlight_med fg:flower"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = " "

[golang]
style = "bg:highlight_med fg:flower"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = " "

[haskell]
style = "bg:highlight_med fg:flower"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = " "

[java]
style = "bg:highlight_med fg:flower"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = " "

[julia]
style = "bg:highlight_med fg:flower"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = " "

[nodejs]
style = "bg:highlight_med fg:flower"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:highlight_med fg:flower"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:highlight_med fg:flower"
format = " [ $symbol$version ]($style)"
disabled = false
symbol = " "

[scala]
style = "bg:highlight_med fg:flower"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = " "

[python]
style = "bg:highlight_med fg:flower"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = ' '

[conda]
style = "bg:highlight_med fg:flower"
format = "[ $symbol$environment ]($style)"
disabled = false
symbol = '🅒 '
[fill]
style = "fg:highlight_med"
symbol = "󰼮󰼮󱑽󱑽󰼮󰥛󰥛󰥛󱑽󰼮󰥛󰼮󱑽󱑽󱑽󰥛󱑽󰼮󰼮"
